# -*- coding: utf-8 -*-
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2023-present Kaleidos INC

# Generated by Django 4.2.3 on 2023-08-22 13:21

import taiga_metrics.collector.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActiveUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        blank=True,
                        default=taiga_metrics.collector.models.uuid_generator,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_uuid", models.UUIDField(verbose_name="user uuid")),
                ("activated", models.DateField(verbose_name="activated date")),
                ("active", models.BooleanField(verbose_name="is active user")),
            ],
            options={
                "verbose_name": "users",
                "verbose_name_plural": "users",
            },
        ),
    ]
