# -*- coding: utf-8 -*-
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2023-present Kaleidos INC

# Generated by Django 4.1.3 on 2023-06-12 18:57

import django.db.models.deletion
import taiga.base.db.models
import taiga.base.utils.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoryAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        blank=True,
                        default=taiga.base.db.models.uuid_generator,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=taiga.base.utils.datetime.aware_utcnow, verbose_name="created at"),
                ),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="story_assignments",
                        to="stories.story",
                        verbose_name="story",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="story_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "story assignment",
                "verbose_name_plural": "story assignments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="storyassignment",
            index=models.Index(fields=["story", "user"], name="stories_ass_story_i_bb03e4_idx"),
        ),
        migrations.AddConstraint(
            model_name="storyassignment",
            constraint=models.UniqueConstraint(
                fields=("story", "user"), name="stories_assignments_storyassignment_unique_story_user"
            ),
        ),
    ]
