# Generated by Django 3.2.12 on 2022-04-01 12:01

from django.db import migrations, models
import django.db.models.deletion


def change_user_to_content_object(apps, schema_editor):
    OutstandingToken = apps.get_model('token_denylist', 'OutstandingToken')
    db_alias = schema_editor.connection.alias

    user_type = apps.get_model("contenttypes", "ContentType").objects.get_by_natural_key("users", "user")

    (OutstandingToken.objects.using(db_alias)
        .filter(user__isnull=False)
        .update(content_type=user_type, object_id=models.F("user_id")))

def change_content_object_to_user(apps, schema_editor):
    ...


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('token_denylist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outstandingtoken',
            name='token_type',
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name='outstandingtoken',
            options={'ordering': ('content_type', 'object_id', 'token_type')},
        ),
        migrations.AddField(
            model_name='outstandingtoken',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='outstandingtoken',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(
            change_user_to_content_object,
            change_content_object_to_user
        ),
        migrations.RemoveField(
            model_name='outstandingtoken',
            name='user',
        ),
    ]
