# -*- coding: utf-8 -*-
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2023-present Kaleidos INC

# Generated by Django 4.1.3 on 2023-06-12 18:57

import taiga.base.db.models
import taiga.base.utils.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        blank=True,
                        default=taiga.base.db.models.uuid_generator,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=taiga.base.utils.datetime.aware_utcnow, verbose_name="created at"),
                ),
                ("title_updated_at", models.DateTimeField(blank=True, null=True, verbose_name="title updated at")),
                (
                    "description_updated_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="description updated at"),
                ),
                ("version", models.PositiveBigIntegerField(default=1, verbose_name="version")),
                ("ref", models.BigIntegerField(db_index=True, default=0, verbose_name="ref")),
                ("title", models.CharField(max_length=500, verbose_name="title")),
                ("description", models.TextField(blank=True, null=True, verbose_name="description")),
                ("order", models.DecimalField(decimal_places=10, default=100, max_digits=16, verbose_name="order")),
            ],
            options={
                "verbose_name": "story",
                "verbose_name_plural": "stories",
                "ordering": ["project", "workflow", "order"],
            },
        ),
    ]
