# -*- coding: utf-8 -*-
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2023-present Kaleidos INC

# Generated by Django 4.1.3 on 2023-06-12 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stories", "0001_initial"),
        ("workflows", "0001_initial"),
        ("stories_assignments", "0001_initial"),
        ("projects", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="assignees",
            field=models.ManyToManyField(
                related_name="stories",
                through="stories_assignments.StoryAssignment",
                to=settings.AUTH_USER_MODEL,
                verbose_name="assignees",
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name="created by"
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="description_updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="description updated by",
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stories",
                to="projects.project",
                verbose_name="project",
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stories",
                to="workflows.workflowstatus",
                verbose_name="status",
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="title_updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="title updated by",
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="workflow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stories",
                to="workflows.workflow",
                verbose_name="workflow",
            ),
        ),
        migrations.AddIndex(
            model_name="story",
            index=models.Index(fields=["project", "ref"], name="stories_sto_project_840ba5_idx"),
        ),
        migrations.AddConstraint(
            model_name="story",
            constraint=models.UniqueConstraint(fields=("project", "ref"), name="projects_unique_refs"),
        ),
    ]
