# -*- coding: utf-8 -*-
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2021-present Kaleidos Ventures SL

# Generated by Django 4.0.6 on 2022-08-08 08:43

from django.contrib.postgres.operations import CreateExtension
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        CreateExtension("unaccent"),
        migrations.RunSQL(
            """
            DROP TEXT SEARCH CONFIGURATION IF EXISTS simple_unaccent cascade;
            CREATE TEXT SEARCH CONFIGURATION simple_unaccent ( COPY = pg_catalog.simple );
            ALTER TEXT SEARCH CONFIGURATION simple_unaccent
            ALTER MAPPING FOR hword, hword_part, word WITH unaccent, simple;
            """
        ),
    ]
