# -*- coding: utf-8 -*-
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2021-present Kaleidos Ventures SL

# Generated by Django 4.1 on 2022-08-17 13:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projecttemplate",
            options={
                "ordering": ["name"],
                "verbose_name": "project template",
                "verbose_name_plural": "project templates",
            },
        ),
        migrations.RemoveField(
            model_name="project",
            name="creation_template",
        ),
        migrations.RemoveField(
            model_name="projecttemplate",
            name="description",
        ),
        migrations.RemoveField(
            model_name="projecttemplate",
            name="order",
        ),
        migrations.AddField(
            model_name="projecttemplate",
            name="workflows",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name="workflows"),
        ),
    ]
