# -*- coding: utf-8 -*-
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2021-present Kaleidos Ventures SL

# Generated by Django 4.1 on 2022-09-02 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_projecttemplate_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["workspace", "slug"], "verbose_name": "project", "verbose_name_plural": "projects"},
        ),
        migrations.AlterModelOptions(
            name="projectrole",
            options={
                "ordering": ["project", "order", "slug"],
                "verbose_name": "project role",
                "verbose_name_plural": "project roles",
            },
        ),
    ]
