# -*- coding: utf-8 -*-
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2021-present Kaleidos Ventures SL

# Generated by Django 4.1 on 2022-09-21 09:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_project_options_alter_projectrole_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="anon_permissions",
        ),
        migrations.AlterField(
            model_name="project",
            name="public_permissions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(
                    choices=[
                        ("add_us", "Add US"),
                        ("comment_us", "Comment US"),
                        ("delete_us", "Delete US"),
                        ("modify_us", "Modify US"),
                        ("view_us", "View US"),
                        ("add_story", "Add story"),
                        ("comment_story", "Comment story"),
                        ("delete_story", "Delete story"),
                        ("modify_story", "Modify story"),
                        ("view_story", "View story"),
                    ]
                ),
                blank=True,
                default=list,
                null=True,
                size=None,
                verbose_name="public permissions",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="workspace_member_permissions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(
                    choices=[
                        ("add_us", "Add US"),
                        ("comment_us", "Comment US"),
                        ("delete_us", "Delete US"),
                        ("modify_us", "Modify US"),
                        ("view_us", "View US"),
                        ("add_story", "Add story"),
                        ("comment_story", "Comment story"),
                        ("delete_story", "Delete story"),
                        ("modify_story", "Modify story"),
                        ("view_story", "View story"),
                    ]
                ),
                blank=True,
                default=list,
                null=True,
                size=None,
                verbose_name="workspace member permissions",
            ),
        ),
        migrations.AlterField(
            model_name="projectrole",
            name="permissions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(
                    choices=[
                        ("add_us", "Add US"),
                        ("comment_us", "Comment US"),
                        ("delete_us", "Delete US"),
                        ("modify_us", "Modify US"),
                        ("view_us", "View US"),
                        ("add_story", "Add story"),
                        ("comment_story", "Comment story"),
                        ("delete_story", "Delete story"),
                        ("modify_story", "Modify story"),
                        ("view_story", "View story"),
                    ]
                ),
                blank=True,
                default=list,
                null=True,
                size=None,
                verbose_name="permissions",
            ),
        ),
    ]
