# -*- coding: utf-8 -*-
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2021-present Kaleidos Ventures SL

# Generated by Django 4.1.1 on 2022-09-21 12:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_remove_project_anon_permissions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="public_permissions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(
                    choices=[
                        ("add_story", "Add story"),
                        ("comment_story", "Comment story"),
                        ("delete_story", "Delete story"),
                        ("modify_story", "Modify story"),
                        ("view_story", "View story"),
                        ("add_task", "Add task"),
                        ("comment_task", "Comment task"),
                        ("delete_task", "Delete task"),
                        ("modify_task", "Modify task"),
                        ("view_task", "View task"),
                    ]
                ),
                blank=True,
                default=list,
                null=True,
                size=None,
                verbose_name="public permissions",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="workspace_member_permissions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(
                    choices=[
                        ("add_story", "Add story"),
                        ("comment_story", "Comment story"),
                        ("delete_story", "Delete story"),
                        ("modify_story", "Modify story"),
                        ("view_story", "View story"),
                        ("add_task", "Add task"),
                        ("comment_task", "Comment task"),
                        ("delete_task", "Delete task"),
                        ("modify_task", "Modify task"),
                        ("view_task", "View task"),
                    ]
                ),
                blank=True,
                default=list,
                null=True,
                size=None,
                verbose_name="workspace member permissions",
            ),
        ),
        migrations.AlterField(
            model_name="projectrole",
            name="permissions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(
                    choices=[
                        ("add_story", "Add story"),
                        ("comment_story", "Comment story"),
                        ("delete_story", "Delete story"),
                        ("modify_story", "Modify story"),
                        ("view_story", "View story"),
                        ("add_task", "Add task"),
                        ("comment_task", "Comment task"),
                        ("delete_task", "Delete task"),
                        ("modify_task", "Modify task"),
                        ("view_task", "View task"),
                    ]
                ),
                blank=True,
                default=list,
                null=True,
                size=None,
                verbose_name="permissions",
            ),
        ),
    ]
