# -*- coding: utf-8 -*-
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2023-present Kaleidos INC

# Generated by Django 4.1.3 on 2023-06-15 08:56

import taiga.base.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflow",
            name="slug",
            field=taiga.base.db.models.fields.LowerSlugField(max_length=250, verbose_name="slug"),
        ),
        migrations.AlterField(
            model_name="workflowstatus",
            name="name",
            field=models.CharField(max_length=30, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="workflowstatus",
            name="order",
            field=models.DecimalField(decimal_places=10, default=100, max_digits=16, verbose_name="order"),
        ),
        migrations.AlterField(
            model_name="workflowstatus",
            name="slug",
            field=taiga.base.db.models.fields.LowerSlugField(max_length=250, verbose_name="slug"),
        ),
        migrations.AddConstraint(
            model_name="workflowstatus",
            constraint=models.UniqueConstraint(
                fields=("workflow", "slug"), name="workflows_workflowstatus_unique_workflow_slug"
            ),
        ),
    ]
