# -*- coding: utf-8 -*-
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2023-present Kaleidos INC

# Generated by Django 4.1.3 on 2023-07-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0002_alter_workflow_slug_alter_workflowstatus_name_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="workflowstatus",
            name="workflows_workflowstatus_unique_workflow_slug",
        ),
        migrations.RemoveIndex(
            model_name="workflowstatus",
            name="workflows_w_workflo_b8ac5c_idx",
        ),
        migrations.RemoveField(
            model_name="workflowstatus",
            name="slug",
        ),
        migrations.AddIndex(
            model_name="workflowstatus",
            index=models.Index(fields=["workflow", "id"], name="workflows_w_workflo_83740e_idx"),
        ),
        migrations.AddConstraint(
            model_name="workflowstatus",
            constraint=models.UniqueConstraint(
                fields=("workflow", "id"), name="workflows_workflowstatus_unique_workflow_id"
            ),
        ),
    ]
