# -*- coding: utf-8 -*-
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2023-present Kaleidos INC

# Generated by Django 4.2.3 on 2023-09-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0003_remove_workflowstatus_workflows_workflowstatus_unique_workflow_slug_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="workflow",
            name="workflows_workflow_unique_project_name",
        ),
        migrations.AlterField(
            model_name="workflow",
            name="order",
            field=models.DecimalField(decimal_places=10, default=100, max_digits=16, verbose_name="order"),
        ),
    ]
