# Generated by Django 2.2.24 on 2021-09-22 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
        ('projects', '0067_auto_20201230_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='workspaces.Workspace', verbose_name='workspace'),
        ),
    ]
