# Generated by Django 2.2.24 on 2021-09-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0068_project_workspace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
