# Generated by Django 2.2.24 on 2022-01-04 10:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0071_auto_20211228_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='anon_permissions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(choices=[('view_project', 'View project'), ('view_us', 'View US'), ('view_tasks', 'View tasks')]), blank=True, default=list, null=True, size=None, verbose_name='anonymous permissions'),
        ),
        migrations.AlterField(
            model_name='project',
            name='public_permissions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(choices=[('view_project', 'View project'), ('add_us', 'Add US'), ('comment_us', 'Comment US'), ('delete_us', 'Delete US'), ('modify_us', 'Modify US'), ('view_us', 'View US'), ('add_task', 'Add task'), ('comment_task', 'Comment task'), ('delete_task', 'Delete task'), ('modify_task', 'Modify task'), ('view_tasks', 'View tasks')]), blank=True, default=list, null=True, size=None, verbose_name='user permissions'),
        ),
    ]
