# Generated by Django 2.2.24 on 2022-01-20 10:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0073_auto_20220118_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='anon_permissions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(choices=[('view_project', 'View project'), ('view_us', 'View US'), ('view_tasks', 'View tasks'), ('view_milestones', 'View milestones')]), blank=True, default=list, null=True, size=None, verbose_name='anonymous permissions'),
        ),
    ]
