# Generated by Django 3.2.12 on 2022-02-14 12:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0076_auto_20220210_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='anon_permissions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(choices=[('view_us', 'View US'), ('view_tasks', 'View tasks'), ('view_milestones', 'View milestones')]), blank=True, default=list, null=True, size=None, verbose_name='anonymous permissions'),
        ),
        migrations.AlterField(
            model_name='project',
            name='public_permissions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(choices=[('add_us', 'Add US'), ('comment_us', 'Comment US'), ('delete_us', 'Delete US'), ('modify_us', 'Modify US'), ('view_us', 'View US'), ('add_task', 'Add task'), ('comment_task', 'Comment task'), ('delete_task', 'Delete task'), ('modify_task', 'Modify task'), ('view_tasks', 'View tasks'), ('view_milestones', 'View milestones')]), blank=True, default=list, null=True, size=None, verbose_name='public permissions'),
        ),
        migrations.AlterField(
            model_name='project',
            name='workspace_member_permissions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(choices=[('add_us', 'Add US'), ('comment_us', 'Comment US'), ('delete_us', 'Delete US'), ('modify_us', 'Modify US'), ('view_us', 'View US'), ('add_task', 'Add task'), ('comment_task', 'Comment task'), ('delete_task', 'Delete task'), ('modify_task', 'Modify task'), ('view_tasks', 'View tasks'), ('view_milestones', 'View milestones')]), blank=True, default=list, null=True, size=None, verbose_name='workspace member permissions'),
        ),
    ]
