# Generated by Django 3.2.12 on 2022-04-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0079_auto_20220405_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='num_emails_sent',
            field=models.IntegerField(default=1, verbose_name='num emails sent'),
        ),
    ]
