# Generated by Django 3.2.12 on 2022-05-11 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0080_invitation_num_emails_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_private',
        ),
    ]
