# -*- coding: utf-8 -*-
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2021-present Kaleidos Ventures SL

# Generated by Django 4.1 on 2022-09-02 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workspace",
            options={"ordering": ["slug"], "verbose_name": "workspace", "verbose_name_plural": "workspaces"},
        ),
        migrations.AlterModelOptions(
            name="workspacerole",
            options={
                "ordering": ["workspace", "order", "slug"],
                "verbose_name": "workspace role",
                "verbose_name_plural": "workspace roles",
            },
        ),
    ]
