# -*- coding: utf-8 -*-
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2021-present Kaleidos Ventures SL

# Generated by Django 4.1.1 on 2022-09-30 08:09

import django.contrib.postgres.fields
import django.db.models.deletion
import taiga.base.db.models
import taiga.base.db.models.fields
import taiga.base.utils.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspaceRole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        blank=True,
                        default=taiga.base.db.models.uuid_generator,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                ("slug", taiga.base.db.models.fields.LowerSlugField(blank=True, max_length=250, verbose_name="slug")),
                (
                    "permissions",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(choices=[("view_workspace", "View workspace")]),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                        verbose_name="permissions",
                    ),
                ),
                (
                    "order",
                    models.BigIntegerField(default=taiga.base.utils.datetime.timestamp_mics, verbose_name="order"),
                ),
                ("is_admin", models.BooleanField(default=False, verbose_name="is_admin")),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="workspaces.workspace",
                        verbose_name="workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "workspace role",
                "verbose_name_plural": "workspace roles",
                "ordering": ["workspace", "order", "slug"],
                "unique_together": {("slug", "workspace")},
            },
        ),
    ]
