# Generated by Django 2.2.24 on 2021-09-24 08:22

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='name',
            field=models.CharField(max_length=40, validators=[django.core.validators.RegexValidator(re.compile('^[a-zA-Z0-9 \\-]+$'), 'Enter a valid name.', 'invalid')], verbose_name='name'),
        ),
    ]
