# Generated by Django 2.2.24 on 2021-10-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_auto_20210924_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='name',
            field=models.CharField(max_length=40, verbose_name='name'),
        ),
    ]
