# Generated by Django 2.2.24 on 2021-11-29 07:06

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0034_workspacerole'),
        ('workspaces', '0003_auto_20211005_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='anon_permissions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(choices=[('view_epics', 'View epic'), ('view_issues', 'View issues'), ('view_milestones', 'View milestones'), ('view_project', 'View project'), ('view_tasks', 'View tasks'), ('view_us', 'View user stories'), ('view_wiki_links', 'View wiki links'), ('view_wiki_pages', 'View wiki pages')]), blank=True, default=list, null=True, size=None, verbose_name='anonymous permissions'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='public_permissions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(choices=[('view_workspace', 'View workspace')]), blank=True, default=list, null=True, size=None, verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='WorkspaceMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workspace_memberships', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_memberships', to='workspaces.Workspace')),
                ('workspace_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_memberships', to='users.WorkspaceRole')),
            ],
            options={
                'verbose_name': 'workspace membership',
                'verbose_name_plural': 'workspace memberships',
                'ordering': ['workspace', 'user__full_name', 'user__username', 'user__email'],
                'unique_together': {('user', 'workspace')},
            },
        ),
        migrations.AddField(
            model_name='workspace',
            name='members',
            field=models.ManyToManyField(related_name='workspaces', through='workspaces.WorkspaceMembership', to=settings.AUTH_USER_MODEL, verbose_name='members'),
        ),
    ]
