# Generated by Django 2.2.24 on 2021-12-01 11:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0004_auto_20211129_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created date'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='modified_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='modified date'),
        ),
    ]
