# Generated by Django 2.2.24 on 2021-12-28 06:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0005_auto_20211201_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='anon_permissions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, null=True, size=None, verbose_name='anonymous permissions'),
        ),
    ]
