# Generated by Django 2.2.24 on 2022-01-04 10:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0006_auto_20211228_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='anon_permissions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(choices=[('view_project', 'View project'), ('view_us', 'View US'), ('view_tasks', 'View tasks')]), blank=True, default=list, null=True, size=None, verbose_name='anonymous permissions'),
        ),
    ]
