# -*- coding: utf-8 -*-
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2021-present Kaleidos Ventures SL

# Generated by Django 4.1.1 on 2022-09-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_project_options_alter_projectrole_options"),
        ("tasks", "0002_alter_task_options"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="task",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="task",
            name="ref",
            field=models.BigIntegerField(db_index=True, default=0, verbose_name="ref"),
        ),
        migrations.AlterUniqueTogether(
            name="task",
            unique_together={("ref", "project")},
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["project", "ref"], name="tasks_task_project_70fc40_idx"),
        ),
        migrations.RemoveField(
            model_name="task",
            name="reference",
        ),
    ]
