# Generated by Django 2.2.24 on 2021-11-29 07:06

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_auto_20211005_0713'),
        ('users', '0033_role__is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('slug', models.SlugField(blank=True, max_length=250, verbose_name='slug')),
                ('permissions', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(choices=[('view_workspace', 'View workspace')]), blank=True, default=list, null=True, size=None, verbose_name='permissions')),
                ('order', models.IntegerField(default=10, verbose_name='order')),
                ('_is_admin', models.BooleanField(default=False)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_roles', to='workspaces.Workspace', verbose_name='workspace')),
            ],
            options={
                'verbose_name': 'workspace role',
                'verbose_name_plural': 'workspace roles',
                'ordering': ['order', 'slug'],
                'unique_together': {('slug', 'workspace')},
            },
        ),
    ]
