# Generated by Django 3.2.12 on 2022-03-14 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_auto_20220309_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_verification',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='date verification'),
        ),
    ]
