# Generated by Django 3.2.13 on 2022-08-08 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_user_date_activation'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE EXTENSION IF NOT EXISTS unaccent;
            """
        ),
        migrations.RunSQL(
            """
            DROP TEXT SEARCH CONFIGURATION IF EXISTS simple_unaccent cascade;
            CREATE TEXT SEARCH CONFIGURATION simple_unaccent ( COPY = pg_catalog.simple );
            ALTER TEXT SEARCH CONFIGURATION simple_unaccent
            ALTER MAPPING FOR hword, hword_part, word WITH unaccent, simple;
            """
        ),
    ]
