# -*- coding: utf-8 -*-
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2023-present Kaleidos INC

# Generated by Django 4.1.3 on 2023-07-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0002_alter_comment_options_comment_deleted_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="modified_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="modified at"),
        ),
    ]
