# -*- coding: utf-8 -*-
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2023-present Kaleidos INC

# Generated by Django 4.2.3 on 2023-10-23 11:16

import django.contrib.postgres.fields.jsonb
import taiga.base.utils.json
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="content",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=dict,
                encoder=taiga.base.utils.json.JSONEncoder,
                verbose_name="content",
            ),
        ),
    ]
