# -*- coding: utf-8 -*-
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2023-present Kaleidos INC

# Generated by Django 4.1.3 on 2023-06-12 18:57

import re

import django.contrib.auth.models
import django.contrib.postgres.fields.jsonb
import django.core.validators
import django.db.models.deletion
import taiga.base.db.models
import taiga.base.db.models.fields
import taiga.base.utils.colors
import taiga.users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "id",
                    models.UUIDField(
                        blank=True,
                        default=taiga.base.db.models.uuid_generator,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    taiga.base.db.models.fields.LowerCharField(
                        help_text="Required. 255 characters or fewer. Letters, numbers and /./-/_ characters",
                        max_length=255,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                re.compile("^[\\w.-]+$"), "Enter a valid username.", "invalid"
                            )
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "email",
                    taiga.base.db.models.fields.LowerEmailField(
                        max_length=255, unique=True, verbose_name="email address"
                    ),
                ),
                (
                    "color",
                    models.IntegerField(
                        blank=True, default=taiga.base.utils.colors.generate_random_color, verbose_name="color"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="Designates whether this user should be treated as active.",
                        verbose_name="active",
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=256, null=True, verbose_name="full name")),
                ("accepted_terms", models.BooleanField(default=True, verbose_name="accepted terms")),
                (
                    "lang",
                    models.CharField(
                        default=taiga.users.models.default_language, max_length=20, verbose_name="language"
                    ),
                ),
                ("date_joined", models.DateTimeField(auto_now_add=True, verbose_name="date joined")),
                (
                    "date_verification",
                    models.DateTimeField(blank=True, default=None, null=True, verbose_name="date verification"),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "ordering": ["username"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="AuthData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        blank=True,
                        default=taiga.base.db.models.uuid_generator,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", taiga.base.db.models.fields.LowerSlugField(verbose_name="key")),
                ("value", models.CharField(max_length=300, verbose_name="value")),
                ("extra", django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name="extra")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auth_data",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "user's auth data",
                "verbose_name_plural": "user's auth data",
                "ordering": ["user", "key"],
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["username"], name="users_user_usernam_65d164_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="users_user_email_6f2530_idx"),
        ),
        migrations.AddIndex(
            model_name="authdata",
            index=models.Index(fields=["user", "key"], name="users_authd_user_id_d24d4c_idx"),
        ),
        migrations.AddConstraint(
            model_name="authdata",
            constraint=models.UniqueConstraint(fields=("user", "key"), name="users_authdata_unique_user_key"),
        ),
    ]
