# -*- coding: utf-8 -*-
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2023-present Kaleidos INC

# Generated by Django 4.1.3 on 2023-06-12 18:57

import functools

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
import taiga.base.db.models
import taiga.base.db.models.fields
import taiga.base.utils.datetime
import taiga.base.utils.files
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        blank=True,
                        default=taiga.base.db.models.uuid_generator,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=taiga.base.utils.datetime.aware_utcnow, verbose_name="created at"),
                ),
                ("modified_at", models.DateTimeField(auto_now=True, verbose_name="modified at")),
                ("name", models.CharField(max_length=80, verbose_name="name")),
                ("description", models.CharField(blank=True, max_length=220, null=True, verbose_name="description")),
                ("color", models.IntegerField(blank=True, default=1, verbose_name="color")),
                (
                    "logo",
                    models.FileField(
                        blank=True,
                        max_length=500,
                        null=True,
                        upload_to=functools.partial(
                            taiga.base.utils.files.get_obfuscated_file_path, *(), **{"base_path": "project"}
                        ),
                        verbose_name="logo",
                    ),
                ),
                (
                    "public_permissions",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(
                            choices=[
                                ("add_story", "Add story"),
                                ("comment_story", "Comment story"),
                                ("delete_story", "Delete story"),
                                ("modify_story", "Modify story"),
                                ("view_story", "View story"),
                            ]
                        ),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                        verbose_name="public permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "project",
                "verbose_name_plural": "projects",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProjectTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        blank=True,
                        default=taiga.base.db.models.uuid_generator,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=taiga.base.utils.datetime.aware_utcnow, verbose_name="created at"),
                ),
                ("modified_at", models.DateTimeField(auto_now=True, verbose_name="modified at")),
                ("name", models.CharField(max_length=250, verbose_name="name")),
                (
                    "slug",
                    taiga.base.db.models.fields.LowerSlugField(
                        blank=True, max_length=250, unique=True, verbose_name="slug"
                    ),
                ),
                ("roles", django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name="roles")),
                (
                    "workflows",
                    django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name="workflows"),
                ),
            ],
            options={
                "verbose_name": "project template",
                "verbose_name_plural": "project templates",
                "ordering": ["name"],
            },
        ),
        migrations.AddIndex(
            model_name="projecttemplate",
            index=models.Index(fields=["slug"], name="projects_pr_slug_28d8d6_idx"),
        ),
        migrations.AddField(
            model_name="project",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name="created by"
            ),
        ),
    ]
