# -*- coding: utf-8 -*-
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2023-present Kaleidos INC

# Generated by Django 4.2.3 on 2023-08-03 12:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_remove_projecttemplate_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.CharField(blank=True, default="", max_length=220, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="project",
            name="public_permissions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(
                    choices=[
                        ("add_story", "Add story"),
                        ("comment_story", "Comment story"),
                        ("delete_story", "Delete story"),
                        ("modify_story", "Modify story"),
                        ("view_story", "View story"),
                    ]
                ),
                default=list,
                size=None,
                verbose_name="public permissions",
            ),
        ),
    ]
