name: Front - tests

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - javascript/**
  pull_request:
    branches: ["*"]
    paths:
      - javascript/**

jobs:
  linters:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Node
        uses: actions/setup-node@v3
        with:
          node-version-file: "./javascript/.nvmrc"
          cache: "npm"
          cache-dependency-path: javascript/package-lock.json

      - name: Install dependencies
        working-directory: ./javascript
        run: npm ci
        shell: bash

      - name: pass linters
        working-directory: ./javascript
        run: npm run lint

  unit-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Node
        uses: actions/setup-node@v3
        with:
          node-version-file: "./javascript/.nvmrc"
          cache: "npm"
          cache-dependency-path: javascript/package-lock.json

      - name: Install dependencies
        working-directory: ./javascript
        run: npm ci
        shell: bash

      - name: pass unit test
        working-directory: ./javascript
        run: npm run test
